# Generated by Django 5.1.4 on 2025-01-03 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cliente_id_alter_enderecocliente_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('motivo_consulta', models.CharField(max_length=200)),
                ('peso_atual', models.FloatField()),
                ('medicamento_atual', models.TextField(blank=True)),
                ('medicamento_prescritos', models.TextField(blank=True)),
                ('exames', models.TextField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pet')),
            ],
        ),
    ]
